services:
  db:
      image: mysql:latest
      container_name: mysql
      restart: always
      environment:
        MYSQL_DATABASE: database
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
        - ./scripts/mysql-init:/docker-entrypoint-initdb.d
volumes:
  db:
  media-data:
