services:
  db:
      image: mysql
      container_name: database
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  upload:
      image: jyleon/upload_service
      container_name: upload
      restart: always
      environment:
        - MYSQL_HOST=db
      ports:
        - "8080:8080"
      env_file:
        - .env
      volumes:
        - media-data:/media-data
      depends_on:
        - db
  stream:
      image: jyleon/stream_service
      container_name: stream
      restart: always
      environment:
        - MYSQL_HOST=db
      ports:
        - "8090:8090"
      env_file:
        - .env
      volumes:
        - media-data:/media-data
      depends_on:
        - db
volumes:
  db:
  media-data: