FROM ubuntu AS upload_service
RUN apt-get update && apt-get install -y python3 python3-pip pkg-config libmysqlclient-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt --break-system-packages

COPY . ./
EXPOSE 8080
CMD ["python3", "main.py"]
